version: '3'
services:

  client:
    build:
      context: .
    volumes:
      - ./src:/usr/src/app/src
    environment:
      PORT: 80
      REACT_APP_BACKEND_URL: localhost:8080/
      NODE_ENV: development
    ports:
      - 80:80
    stdin_open: true
